# Generated by Django 3.1 on 2020-08-07 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Product filter',
                'verbose_name_plural': 'product filters',
            },
        ),
        migrations.CreateModel(
            name='ProductFilterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('N', 'Number'), ('S', 'String')], default='S', max_length=1)),
                ('product_filter', models.ManyToManyField(related_name='product_filter_value', to='filters.ProductFilter')),
            ],
            options={
                'verbose_name': 'Product variable value',
                'verbose_name_plural': 'product variable values',
            },
        ),
        migrations.CreateModel(
            name='ProductFilterName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_filter', models.ManyToManyField(related_name='product_filter_name', to='filters.ProductFilter')),
            ],
            options={
                'verbose_name': 'Product variable name',
                'verbose_name_plural': 'product variable names',
            },
        ),
    ]
