# Generated by Django 3.1 on 2020-08-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfiltervalue',
            name='product_filter',
        ),
        migrations.RemoveField(
            model_name='productfiltervalue',
            name='value_type',
        ),
        migrations.AddField(
            model_name='productfiltername',
            name='value_type',
            field=models.CharField(choices=[('N', 'Number'), ('S', 'String')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='productfiltervalue',
            name='filter_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_filter_value', to='filters.productfiltername'),
        ),
        migrations.RemoveField(
            model_name='productfiltername',
            name='product_filter',
        ),
        migrations.AddField(
            model_name='productfiltername',
            name='product_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_filter_name', to='filters.productfilter'),
        ),
    ]
