# Generated by Django 3.1 on 2020-08-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variables',
        ),
        migrations.AddField(
            model_name='productvariable',
            name='product',
            field=models.ForeignKey(default='6efeac99-8625-4a7e-8337-7e214e6f2578', on_delete=django.db.models.deletion.CASCADE, to='Shop.product'),
            preserve_default=False,
        ),
    ]
