# Generated by Django 3.1 on 2020-08-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20200807_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilter',
            name='filter_name',
        ),
        migrations.RemoveField(
            model_name='productfilter',
            name='filter_value',
        ),
        migrations.AddField(
            model_name='productfiltername',
            name='product_filter',
            field=models.ManyToManyField(related_name='product_filter_name', to='Shop.ProductFilter'),
        ),
        migrations.AddField(
            model_name='productfiltervalue',
            name='product_filter',
            field=models.ManyToManyField(related_name='product_filter_value', to='Shop.ProductFilter'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='parent',
            field=models.ForeignKey(blank=str, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.catalog'),
        ),
    ]
