# Generated by Django 3.1 on 2020-08-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('Shop', '0003_auto_20200807_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfiltername',
            name='product_filter',
        ),
        migrations.RemoveField(
            model_name='productfiltervalue',
            name='product_filter',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='product_filter',
            field=models.ManyToManyField(related_name='catalog', to='filters.ProductFilter'),
        ),
        migrations.DeleteModel(
            name='ProductFilter',
        ),
        migrations.DeleteModel(
            name='ProductFilterName',
        ),
        migrations.DeleteModel(
            name='ProductFilterValue',
        ),
    ]
