# Generated by Django 3.1 on 2020-08-07 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.TextField()),
                ('postal_address', models.TextField()),
                ('inn', models.IntegerField()),
                ('kpp', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Requisites',
                'verbose_name_plural': 'requisites',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('P', 'Person'), ('C', 'Company')], default='P', max_length=1)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('requisites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.requisites')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
