# Generated by Django 3.1 on 2020-08-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_positions',
        ),
        migrations.AddField(
            model_name='cardposition',
            name='card',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='card_positions', to='basket.card'),
            preserve_default=False,
        ),
    ]
